convoy-gluster:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /etc/docker/plugins:/etc/docker/plugins
  image: lusu777/convoy-agent:latest
  command: volume_agent_glusterfs

convoy-gluster-storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
  volumes:
    - /var/run:/host/var/run
  image: lusu777/convoy-agent:latest
  command: storagepool-agent
